#!/bin/bash
#Luba kasutajale sisestada suvaline täisarv.
#Skript peab arvutama sisestatud arvu numbrite summat
#ja väljastama koos selgitava tekstiga.
echo "Palun sisesta suvaline täisarv"
read arv
summa=0
while [ $arv -ne 0 ]
do
	jaak=$(( $arv % 10 ))
	summa=$(( $summa + $jaak ))
	arv=$(( $arv / 10 ))
done
echo "Selle arvu  numbrite summa on $summa"
#skripti lõpp
