#!/bin/bash
#Koosta skript,mis lubab kasutajale sisestada kuu number (1-12).
#Vastavalt sisestatud kuu numbrile tuleb väljastada kuu nimetus.
#Muude väärtuste korral väljastatakse seletav veateade.
echo "Palun sisesta kuu number:"
read arv
case $arv in
	1) echo "See on jaanuar ";;
	2) echo "See on veebruar";;
	3) echo "See on märts";;
	4) echo "See on aprill";;
	5) echo "See on mai";;
	6) echo "See on juuni";;
	7) echo "See on juuni";;
	8) echo "See on august";;
	9) echo "See on september";;
	10) echo "See on oktoober";;
	11) echo "See on noveber";;
	12) echo "See on detsember";;
	*) echo "Vabandust sellist kuud ei ole";;
esac
